# Jekyll configuration file
title: Ktor
description: Asynchronous framework for web applications
baseurl: "/"
#url: "https://kotlin.github.io"

# Dirs
source: .
destination: ../dist

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - package-list
